### ISSUE TITLE
Mission Log?

### ISSUE THREAD

**Issue by randoomdude** [TojiKitten/FFTA-randomizer#73]
I'm really confused about the Mission Log, i'm not sure what it does, wether it's just for speed run races or not i'm still interested though, does it affect what missions will show in random or story/linear?

**Comment by fgkeiji** [comment]
@randoomdude, sorry for the delay on this response, but thanks for reaching out.

The mission log is there to search for basic mission information. Check off "All Missions" and use the search bar to look up different missions in the game. Originally, I added it to help use as a tracker for speed running, but it's now really just for reference/show. Let me know if this helps!
