### ISSUE TITLE
Too many Mythril Staffs

### ISSUE THREAD

**Issue by FelixGrafschmidt** [TojiKitten/FFTA-randomizer#78]
I know that RNG can be weird sometimes but I think it is a little weird that I have received five Mythril Staffs as mission rewards with having only played 15 missions. This is the only item I received multiple copies of at this point. The next main mission will give me another one.
[first.zip](https://github.com/TojiKitten/FFTA-randomizer/files/8753870/first.zip)

**Comment by fgkeiji** [comment]
Finished Herb Picking only and saw different reward items (no Mythril Staves). The rewards looked like they were randomized sufficiently in the hex as well, but it's much harder for me to see without a debug tool.

I'll leave this open as a request for the following:
1. Visualizer in the randomizer for the mission reward sets
2. A setting for mission rewards to have unique items in all sets (might already be done?)

**Comment by FelixGrafschmidt** [comment]
Yeah, I think Herb Picking did not yield a Mythril Rod. But thank you for your response as well as a possible way for future improvement.

**Comment by fgkeiji** [comment]
This has been added to 3.2.3. If you reload your file with the same settings it will update the reward sets without duplicates. It won't remove the Mythril Staves you already have, but at least you have one per party member 🙃 

I did not add the visualizer for this change, so I'll add that to the Project as an enhancement.
