### ISSUE TITLE
No Clan EXP / Clan Levels / Clan Skills

### ISSUE THREAD

**Issue by FelixGrafschmidt** [TojiKitten/FFTA-randomizer#79]
I have now defeated the first two Totema but have still to gain any Clan Exp. There are already 4 or 5 missions I cannot do since they require specific Clan Skills. I did not choose the "Disable Clans" option.
[second.zip](https://github.com/TojiKitten/FFTA-randomizer/files/8762871/second.zip)

(It has been some time since I played the game regularly. A quick Google search did not help either. If there was anything else I have to do to enable Clan EXP, I am very sorry. I do already have acces to the Clan menu.)

**Comment by fgkeiji** [comment]
Was able to recreate this one. Unfortunately, I don't think there's a workaround for this. I suspect it has something to do with the "Skip cutscenes" option and a flag not being properly set. This should normally unlock after Thesis Hunt. If I remember correctly, it's only dispatch missions that have clan skill requirements, so you should be able to finish all of the combat type of missions.

**Comment by FelixGrafschmidt** [comment]
Unfortunately, no, there are also regular missions with clan skill requirements, From where I am at the moment I can see "S.O.S." and "A challenge". The latter is a on-map-encounter-mission (don't know if they have a proper name) but S.O.S. is a regular mission.

**Comment by fgkeiji** [comment]
Thanks for those examples. Looks like S.O.S. requires Tracking 7. Let me see what I'm able to do as a short term fix.

**Comment by FelixGrafschmidt** [comment]
Seems to work as described, at least in my test. Thank you very much for the fix.
