### ISSUE TITLE
A JavaScript error occurred in the main process Uncaught Exception

### ISSUE THREAD

**Issue by BloodDragooner2** [TojiKitten/FFTA-randomizer#84]
` TypeError. Cannot read property 'itemlD' of undefined
at
at Object.e.setUnitData
at
at Array.forEach (<anonymous>)
at N.handleRandomEnemies
at Object.e.randomizeFFTA
at IpcMainlmpl.<anonymous>
at IpcMainlmpl.emit (events.js:315:20)
at Object.<anonymous> (electron/js2c/browser_init.js:157:8980)
at Object.emit (events.js:315:20)`
I don't know why this started, the only thing i did was try and beautify the `RandomLinearStory` JSON. I do not know if anyone is still working on this, but, I'd appreciate help!

**Comment by fgkeiji** [comment]
@BloodDragooner2, based on the error I'm wondering if the item id key was changed to something else like a 1 or a lower case L. Double check that and if there is still and issue feel free to attach the JSON and I can take a look.

**Comment by BloodDragooner2** [comment]
Hi, sorry for the late reply. I tried checking if it still happened on a fresh Virtual Machine, and indeed, it crashes. The ROM creation is the problem, and not the JSON, my bad! Here it is 
`{"generalSettings":{"romLoaded":true,"currentPage":"jobs","isRandomized":false,"raceMode":false,"randomizerSeed":20221209,"cutscenes":"all","laws":"normal","startingGold":5000,"frostyMageBoost":false,"disableClans":true,"quickOptions":true,"noJudgeTurn":true,"mpRegen":"normal"},"missionSettings":{"storySetting":"linear","storyLength":5,"missionScaling":"average","missionScalingValue":1,"missionRewards":"normal","disableRewardPreview":false,"apBoost":-1,"gilReward":-1,"randomEnemies":false,"enemyAbilityPercentage":0,"randomEnemyItems":false},"partySettings":{"partyRNGEnabled":true,"partyMembers":[{"name":"Marche","raceChangeable":true,"race":"human","job":"random","rngEquip":false,"level":3,"masterType":"abilities","masteredAbilities":0},{"name":"Montblanc","raceChangeable":true,"race":"moogle","job":"random","rngEquip":false,"level":3,"masterType":"abilities","masteredAbilities":0},{"name":"Member 3","raceChangeable":true,"race":"random","job":"random","rngEquip":false,"level":3,"masterType":"abilities","masteredAbilities":0},{"name":"Member 4","raceChangeable":true,"race":"random","job":"random","rngEquip":false,"level":3,"masterType":"abilities","masteredAbilities":0},{"name":"Member 5","raceChangeable":true,"race":"random","job":"random","rngEquip":false,"level":3,"masterType":"abilities","masteredAbilities":0},{"name":"Member 6","raceChangeable":true,"race":"random","job":"random","rngEquip":false,"level":3,"masterType":"abilities","masteredAbilities":0}]},"jobSettings":{"jobRequirements":"normal","randomizeJobEquipment":true,"randomizedWeaponsAmount":0,"randomizedArmorAmount":0,"randomizeResistances":false,"human":[{"jobName":"Soldier","enabled":true},{"jobName":"Paladin","enabled":true},{"jobName":"Fighter","enabled":true},{"jobName":"Thief","enabled":true},{"jobName":"Ninja","enabled":true},{"jobName":"White Mage","enabled":true},{"jobName":"Black Mage","enabled":true},{"jobName":"Illusionist","enabled":true},{"jobName":"Blue Mage","enabled":true},{"jobName":"Archer","enabled":true},{"jobName":"Hunter","enabled":true}],"bangaa":[{"jobName":"Warrior","enabled":true},{"jobName":"Dragoon","enabled":true},{"jobName":"Defender","enabled":true},{"jobName":"Gladiator","enabled":true},{"jobName":"White Monk","enabled":true},{"jobName":"Bishop","enabled":true},{"jobName":"Templar","enabled":true}],"nuMou":[{"jobName":"White Mage","enabled":true},{"jobName":"Black Mage","enabled":true},{"jobName":"Time Mage","enabled":true},{"jobName":"Illusionist","enabled":true},{"jobName":"Alchemist","enabled":true},{"jobName":"Beastmaster","enabled":true},{"jobName":"Morpher","enabled":true},{"jobName":"Sage","enabled":true}],"viera":[{"jobName":"Fencer","enabled":true},{"jobName":"Elementalist","enabled":true},{"jobName":"Red Mage","enabled":true},{"jobName":"White Mage","enabled":true},{"jobName":"Summoner","enabled":true},{"jobName":"Archer","enabled":true},{"jobName":"Assassin","enabled":true},{"jobName":"Sniper","enabled":true}],"moogle":[{"jobName":"Animist","enabled":true},{"jobName":"Mog Knight","enabled":true},{"jobName":"Gunner","enabled":true},{"jobName":"Thief","enabled":true},{"jobName":"Juggler","enabled":true},{"jobName":"Gadgeteer","enabled":true},{"jobName":"Black Mage","enabled":true},{"jobName":"Time Mage","enabled":true}]},"abilitySettings":{"abilities":"normal","bannedAbilities":[]},"itemSettings":{"shopItems":"default","randomChance":50,"bannedItems":[]},"missionLogSettings":{"showAllMissions":false,"showCompletedMissions":false,"showRepeatableMissions":true,"showMissingMissionItems":true,"missionItems":{}}}`

**Comment by fgkeiji** [comment]
@BloodDragooner2, sorry about the late reply on my end. It looks like the issue is that you enabled random job equipment and set the number of random weapons and armor types to 0.

We can keep this one open for myself as a reminder that this case should be handled to at least default to 1 for both if 0 is detected.

**Comment by BloodDragooner2** [comment]
Aaah, I see! Thank you! I will check again sometime. Thank you for your help!!
